name: Update GitHub Profile

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update GitHub Stats
        uses: anuraghazra/github-readme-stats@latest
        with:
          user: HarshSharmaQA
          hide_border: false
          theme: dark

      - name: Update Contribution Stats
        uses: Luminousmen/contributions@latest
        with:
          username: HarshSharmaQA
          output: README.md

      - name: Update Dev Quotes
        run: echo "![Quote](https://quotes-github-readme.vercel.app/api?type=horizontal&theme=radical)" >> README.md

      - name: Auto Commit & Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "🔄 Auto-update README"
          git push
